uam_maintenance_admin_index:
    path: /maintenance/admin
    defaults:
        _controller: UAMMaintenanceBundle:Admin:index

uam_maintenance_admin_list:
    path: /maintenance/list
    defaults:
        _controller: UAMMaintenanceBundle:Admin:list
        _format: json
    requirements:
        _format: json

uam_maintenance_admin_create:
    path: /maintenance/create
    defaults:
        _controller: UAMMaintenanceBundle:Admin:create

uam_maintenance_admin_edit:
    path: /maintenance/edit/{id}
    defaults:
        _controller: UAMMaintenanceBundle:Admin:edit
    requirements:
        id: \d+

uam_maintenance_admin_delete:
    path: /maintenance/delete/{id}
    defaults:
        _controller: UAMMaintenanceBundle:Admin:delete
    requirements:
        id: \d+